[package]
name = "uniffi-builder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"

[dependencies]
uniffi = { version = "0.28.1", features = ["build", "cli"] }
