name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Expo Module scripts
      run: | 
        npm install
        npm run prepare
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build Rust
      run: cd rust/expo_rust_demo_module && make prepare-android-cargo-ndk && make prepare-android && make all-android
  
    - name: Build Android example project
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
      run: |
        cd example/android
        ./gradlew assembleDebug --no-daemon --max-workers 2
